server {
    listen 9004;
    server_name localhost;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header X-Forwarded-For $remote_addr;
    add_header 'Access-Control-Allow-Origin' '*';
    add_header 'Access-Control-Allow-Methods' 'OPTIONS, GET, POST';
    add_header 'Access-Control-Allow-Headers' 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization';
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    
    location /api/File/Image/annexpic/ {
        alias /app/cloudiot/Upload/SystemFile/;
        autoindex on;
    }

    location  /api/File/Image/annex/ {
        alias /app/cloudiot/Upload/SystemFile/;
        autoindex on;
    }

    location /api/ {
        rewrite ^/api/(.*) /$1 break;
        proxy_pass http://localhost:9081;
    }
    
    location /avatar/ {
        alias  /app/cloudiot/Upload/Avatar/;
        autoindex on;
    }
    
    location /webhook/ {
        rewrite ^/(.*) /$1 break;
        proxy_pass http://localhost:9081;
    }
    
    location /device {   
        proxy_pass http://localhost:9081/device;
        proxy_http_version 1.1;    
        proxy_set_header Upgrade $http_upgrade;    
        proxy_set_header Connection "Upgrade";    
        proxy_set_header X-real-ip $remote_addr;
        proxy_set_header X-Forwarded-For $remote_addr;
    }
    
    location /mes {
        root D:/tmp/publish/cloudiothtml;
        try_files $uri /index.html;
        index index.html index.htm;
    }   
    
    location / {
        root  D:/tmp/publish/cloudiothtml;
        try_files $uri /index.html;
        index  index.html index.htm;
    }
}
